import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pricing Page",
  description: "Generated by Next.js",
  keywords: ["Pricing Page", "next.js", "react"],
};

export default function PricingPage() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <h1 className="text-4xl font-bold">Pricing Page</h1>
      <p className="mt-4 text-lg text-gray-600">
        This is the pricing page of the application.
      </p>
    </div>
  );
}